singularity exec --bind /scratch/a.pfb:/scratch/a.pfb --bind /home/a.pfb:/home/a.pfb /scratch/a.pfb/sw_imgs/au-eoed-py-dev.sif eoddpluginreport.py -c /scratch/a.pfb/gmw_monitoring/scripts/eodd_config_west_africa/EODataDownConfig_psql.json -s LandsatGOOG -p LandsatClearSky -o /scratch/a.pfb/gmw_monitoring/sen_reports/LandsatGOOG_wa_$(date +'%Y%m%d')_ClearSky.json
singularity exec --bind /scratch/a.pfb:/scratch/a.pfb --bind /home/a.pfb:/home/a.pfb /scratch/a.pfb/sw_imgs/au-eoed-py-dev.sif eoddpluginreport.py -c /scratch/a.pfb/gmw_monitoring/scripts/eodd_config_west_africa/EODataDownConfig_psql.json -s Sentinel2GOOG -p Sentinel2ClearSky -o /scratch/a.pfb/gmw_monitoring/sen_reports/Sentinel2GOOG_wa_$(date +'%Y%m%d')_ClearSky.json

singularity exec --bind /scratch/a.pfb:/scratch/a.pfb --bind /home/a.pfb:/home/a.pfb /scratch/a.pfb/sw_imgs/au-eoed-py-dev.sif eoddpluginreport.py -c /scratch/a.pfb/gmw_monitoring/scripts/eodd_config_west_africa/EODataDownConfig_psql.json -s LandsatGOOG -p LandsatGMWScnChange -o /scratch/a.pfb/gmw_monitoring/sen_reports/LandsatGOOG_wa_$(date +'%Y%m%d')_GMWScnChange.json
singularity exec --bind /scratch/a.pfb:/scratch/a.pfb --bind /home/a.pfb:/home/a.pfb /scratch/a.pfb/sw_imgs/au-eoed-py-dev.sif eoddpluginreport.py -c /scratch/a.pfb/gmw_monitoring/scripts/eodd_config_west_africa/EODataDownConfig_psql.json -s Sentinel1ASF -p Sentinel1GMWScnChange -o /scratch/a.pfb/gmw_monitoring/sen_reports/Sentinel1ASF_wa_$(date +'%Y%m%d')_GMWScnChange.json
singularity exec --bind /scratch/a.pfb:/scratch/a.pfb --bind /home/a.pfb:/home/a.pfb /scratch/a.pfb/sw_imgs/au-eoed-py-dev.sif eoddpluginreport.py -c /scratch/a.pfb/gmw_monitoring/scripts/eodd_config_west_africa/EODataDownConfig_psql.json -s Sentinel2GOOG -p Sentinel2GMWScnChange -o /scratch/a.pfb/gmw_monitoring/sen_reports/Sentinel2GOOG_wa_$(date +'%Y%m%d')_GMWScnChange.json

singularity exec --bind /scratch/a.pfb:/scratch/a.pfb --bind /home/a.pfb:/home/a.pfb /scratch/a.pfb/sw_imgs/au-eoed-py-dev.sif eoddpluginreport.py -c /scratch/a.pfb/gmw_monitoring/scripts/eodd_config_west_africa/EODataDownConfig_psql.json -s LandsatGOOG -p LandsatGMWChangeFnl -o /scratch/a.pfb/gmw_monitoring/sen_reports/LandsatGOOG_wa_$(date +'%Y%m%d')_GMWChange.json
singularity exec --bind /scratch/a.pfb:/scratch/a.pfb --bind /home/a.pfb:/home/a.pfb /scratch/a.pfb/sw_imgs/au-eoed-py-dev.sif eoddpluginreport.py -c /scratch/a.pfb/gmw_monitoring/scripts/eodd_config_west_africa/EODataDownConfig_psql.json -s Sentinel1ASF -p Sentinel1GMWChangeFnl -o /scratch/a.pfb/gmw_monitoring/sen_reports/Sentinel1ASF_wa_$(date +'%Y%m%d')_GMWChange.json
singularity exec --bind /scratch/a.pfb:/scratch/a.pfb --bind /home/a.pfb:/home/a.pfb /scratch/a.pfb/sw_imgs/au-eoed-py-dev.sif eoddpluginreport.py -c /scratch/a.pfb/gmw_monitoring/scripts/eodd_config_west_africa/EODataDownConfig_psql.json -s Sentinel2GOOG -p Sentinel2GMWChangeFnl -o /scratch/a.pfb/gmw_monitoring/sen_reports/Sentinel2GOOG_wa_$(date +'%Y%m%d')_GMWChange.json

singularity exec --bind /scratch/a.pfb:/scratch/a.pfb --bind /home/a.pfb:/home/a.pfb /scratch/a.pfb/sw_imgs/au-eoed-py-dev.sif eoddpluginreport.py -c /scratch/a.pfb/gmw_monitoring/scripts/eodd_config_west_africa/EODataDownConfig_psql.json -s LandsatGOOG -p GenChngSummaryFeats -o /scratch/a.pfb/gmw_monitoring/sen_reports/LandsatGOOG_wa_$(date +'%Y%m%d')_ChngSummary.json
singularity exec --bind /scratch/a.pfb:/scratch/a.pfb --bind /home/a.pfb:/home/a.pfb /scratch/a.pfb/sw_imgs/au-eoed-py-dev.sif eoddpluginreport.py -c /scratch/a.pfb/gmw_monitoring/scripts/eodd_config_west_africa/EODataDownConfig_psql.json -s Sentinel1ASF -p GenChngSummaryFeats -o /scratch/a.pfb/gmw_monitoring/sen_reports/Sentinel1ASF_wa_$(date +'%Y%m%d')_ChngSummary.json
singularity exec --bind /scratch/a.pfb:/scratch/a.pfb --bind /home/a.pfb:/home/a.pfb /scratch/a.pfb/sw_imgs/au-eoed-py-dev.sif eoddpluginreport.py -c /scratch/a.pfb/gmw_monitoring/scripts/eodd_config_west_africa/EODataDownConfig_psql.json -s Sentinel2GOOG -p GenChngSummaryFeats -o /scratch/a.pfb/gmw_monitoring/sen_reports/Sentinel2GOOG_wa_$(date +'%Y%m%d')_ChngSummary.json

singularity exec --bind /scratch/a.pfb:/scratch/a.pfb --bind /home/a.pfb:/home/a.pfb /scratch/a.pfb/sw_imgs/au-eoed-py-dev.sif eoddpluginreport.py -c /scratch/a.pfb/gmw_monitoring/scripts/eodd_config_west_africa/EODataDownConfig_psql.json -s LandsatGOOG -p CreateSummaryVecFeats -o /scratch/a.pfb/gmw_monitoring/sen_reports/LandsatGOOG_wa_$(date +'%Y%m%d')_ChngSummaryVec.json
singularity exec --bind /scratch/a.pfb:/scratch/a.pfb --bind /home/a.pfb:/home/a.pfb /scratch/a.pfb/sw_imgs/au-eoed-py-dev.sif eoddpluginreport.py -c /scratch/a.pfb/gmw_monitoring/scripts/eodd_config_west_africa/EODataDownConfig_psql.json -s Sentinel1ASF -p CreateSummaryVecFeats -o /scratch/a.pfb/gmw_monitoring/sen_reports/Sentinel1ASF_wa_$(date +'%Y%m%d')_ChngSummaryVec.json
singularity exec --bind /scratch/a.pfb:/scratch/a.pfb --bind /home/a.pfb:/home/a.pfb /scratch/a.pfb/sw_imgs/au-eoed-py-dev.sif eoddpluginreport.py -c /scratch/a.pfb/gmw_monitoring/scripts/eodd_config_west_africa/EODataDownConfig_psql.json -s Sentinel2GOOG -p CreateSummaryVecFeats -o /scratch/a.pfb/gmw_monitoring/sen_reports/Sentinel2GOOG_wa_$(date +'%Y%m%d')_ChngSummaryVec.json
